name: Docker Image CI/CD
on:
  push:
    branches: [ app ]
jobs:
  build: 
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - name: Build Image
        run: |
          docker build -t omdbsd/chineseocr  .
      - name: Login to Registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Image
        run: |
          docker push omdbsd/chineseocr
