name: Build and Push

on:
  push:
    branches:
      - app

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      run: |
        docker buildx create --use
    - name: Set date
      id: date
      run: echo "::set-output name=date::$(date +'%m-%d-%Y')"
    - name: Authenticate
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push image
      run: |
        docker buildx build \
          --file ./Dockerfile \
          --platform linux/amd64\
          --tag omdbsd/chineseocr:${{ steps.date.outputs.date }} \
          --push .
